apiVersion: afka.strimzi.io/v1
kind: Kafka
metadata:
  name: demo-kafka-cluster
  namespace: spring-boot-demo
  labels:
    app: kafka
spec:
  # Kafka Configuration (KRaft mode - no Zookeeper needed!)
  kafka:
    # Kafka version
    version: 4.1.1

    # 3 brokers for production high availability
    replicas: 3

    # Listeners for client connections
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true

    # Kafka configuration
    config:
      # Replication settings for production
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2

      # Automatic topic creation
      auto.create.topics.enable: true

      # Log retention (7 days)
      log.retention.hours: 168
      log.segment.bytes: 1073741824  # 1GB

      # Compression
      compression.type: lz4

      # Performance tuning
      num.network.threads: 3
      num.io.threads: 8
      socket.send.buffer.bytes: 102400
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600

    # Storage configuration
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 20Gi
          deleteClaim: false
          class: ""  # Use default storage class

    # Resource limits
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m

    # JVM Options
    jvmOptions:
      -Xms: 768m
      -Xmx: 768m

    # Pod Disruption Budget (keep at least 2 brokers available)
    template:
      pod:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: strimzi.io/name
                        operator: In
                        values:
                          - demo-kafka-cluster-kafka
                  topologyKey: kubernetes.io/hostname

    # Metrics configuration for Prometheus
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml

  # Entity Operator (manages topics and users)
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
    userOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m

  # Cruise Control (optional - for rebalancing)
  cruiseControl:
    resources:
      requests:
        memory: 256Mi
        cpu: 200m
      limits:
        memory: 512Mi
        cpu: 500m

---
# Kafka Metrics ConfigMap for Prometheus
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics
  namespace: spring-boot-demo
  labels:
    app: strimzi
data:
  kafka-metrics-config.yml: |
    # Kafka JMX metrics configuration
    lowercaseOutputName: true
    rules:
      # Kafka broker metrics
      - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
        labels:
          clientId: "$3"
          topic: "$4"
          partition: "$5"
      - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+), brokerPort=(.+)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
        labels:
          clientId: "$3"
          broker: "$4:$5"
      - pattern: kafka.server<type=(.+), name=(.+)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
      # Kafka network metrics
      - pattern: kafka.network<type=(.+), name=(.+)><>Value
        name: kafka_network_$1_$2
        type: GAUGE
      # Kafka log metrics
      - pattern: kafka.log<type=(.+), name=(.+)><>Value
        name: kafka_log_$1_$2
        type: GAUGE
      # Controller metrics
      - pattern: kafka.controller<type=(.+), name=(.+)><>Value
        name: kafka_controller_$1_$2
        type: GAUGE
